# Generated by Django 5.2.8 on 2025-11-10 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for the API key', max_length=100)),
                ('key_type', models.CharField(choices=[('mobile_android', 'اپ اندروید'), ('mobile_ios', 'اپ iOS'), ('web_app', 'اپلیکیشن وب'), ('third_party', 'Third Party')], default='mobile_android', max_length=20)),
                ('api_key', models.CharField(max_length=64, unique=True)),
                ('api_secret', models.CharField(blank=True, help_text='For HMAC authentication', max_length=128)),
                ('can_read_devices', models.BooleanField(default=True)),
                ('can_write_devices', models.BooleanField(default=False)),
                ('can_read_tracking', models.BooleanField(default=True)),
                ('can_write_tracking', models.BooleanField(default=False)),
                ('can_manage_geofences', models.BooleanField(default=False)),
                ('rate_limit_per_hour', models.PositiveIntegerField(default=1000)),
                ('rate_limit_per_day', models.PositiveIntegerField(default=10000)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique device identifier', max_length=255, unique=True)),
                ('token_type', models.CharField(choices=[('fcm', 'Firebase Cloud Messaging'), ('apns', 'Apple Push Notification Service')], max_length=10)),
                ('token', models.TextField(help_text='Push notification token')),
                ('device_model', models.CharField(blank=True, max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=50)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Token',
                'verbose_name_plural': 'Device Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('webhook_type', models.CharField(choices=[('location_update', 'به\u200cروزرسانی موقعیت'), ('geofence_alert', 'هشدار منطقه محدود'), ('device_status', 'وضعیت دستگاه'), ('subscription_update', 'به\u200cروزرسانی اشتراک')], max_length=20)),
                ('url', models.URLField(help_text='Webhook endpoint URL')),
                ('secret', models.CharField(help_text='Webhook secret for HMAC verification', max_length=128)),
                ('headers', models.JSONField(default=dict, help_text='Custom headers to send with webhook')),
                ('is_active', models.BooleanField(default=True)),
                ('retry_count', models.PositiveIntegerField(default=3)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=500)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('status_code', models.PositiveIntegerField()),
                ('response_size', models.PositiveIntegerField(default=0, help_text='Response size in bytes')),
                ('duration_ms', models.PositiveIntegerField(help_text='Request duration in milliseconds')),
                ('log_type', models.CharField(choices=[('request', 'درخواست'), ('response', 'پاسخ'), ('error', 'خطا')], default='request', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('request_data', models.JSONField(default=dict, help_text='Request payload (sanitized)')),
                ('response_data', models.JSONField(default=dict, help_text='Response data (sanitized)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.apikey')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Log',
                'verbose_name_plural': 'API Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['api_key', '-created_at'], name='api_apilog_api_key_96f762_idx'), models.Index(fields=['user', '-created_at'], name='api_apilog_user_id_50746e_idx'), models.Index(fields=['endpoint', 'status_code'], name='api_apilog_endpoin_b3a9d3_idx'), models.Index(fields=['created_at'], name='api_apilog_created_4fcf0c_idx')],
            },
        ),
    ]
