# Generated by Django 5.2.8 on 2025-11-10 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gps_devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('basic', 'پایه'), ('premium', 'پریمیوم'), ('enterprise', 'سازمانی')], default='basic', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price_per_year', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_devices', models.PositiveIntegerField(default=1, help_text='Maximum number of devices allowed')),
                ('storage_days', models.PositiveIntegerField(default=30, help_text='Historical data storage in days')),
                ('real_time_updates', models.BooleanField(default=True)),
                ('geofencing_alerts', models.BooleanField(default=True)),
                ('sms_alerts', models.BooleanField(default=False)),
                ('email_alerts', models.BooleanField(default=True)),
                ('api_access', models.BooleanField(default=False)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'ماهانه'), ('yearly', 'سالانه')], default='yearly', max_length=10)),
                ('trial_days', models.PositiveIntegerField(default=0, help_text='Free trial period in days')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['price_per_year'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'دوره آزمایشی'), ('active', 'فعال'), ('expired', 'منقضی شده'), ('cancelled', 'لغو شده'), ('suspended', 'معلق')], default='trial', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'ماهانه'), ('yearly', 'سالانه')], default='yearly', max_length=10)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('devices', models.ManyToManyField(blank=True, related_name='subscriptions', to='gps_devices.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'plan')},
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('subscription', 'اشتراک'), ('renewal', 'تمدید'), ('upgrade', 'ارتقا')], default='subscription', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_method', models.CharField(help_text='e.g., zarinpal, card_to_card', max_length=50)),
                ('is_successful', models.BooleanField(default=False)),
                ('failure_reason', models.TextField(blank=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('effective_date', models.DateTimeField(blank=True, help_text='When subscription was extended', null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'Payment Record',
                'verbose_name_plural': 'Payment Records',
                'ordering': ['-payment_date'],
            },
        ),
    ]
