# Generated by Django 5.2.8 on 2025-11-10 18:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('gateway_type', models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('mellat', 'بانک ملت'), ('saderat', 'بانک صادرات'), ('parsian', 'بانک پارسیان'), ('card_to_card', 'کارت به کارت')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('merchant_id', models.CharField(blank=True, max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=200)),
                ('api_secret', models.CharField(blank=True, max_length=200)),
                ('callback_url', models.URLField(blank=True)),
                ('success_url', models.URLField(blank=True)),
                ('failure_url', models.URLField(blank=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, default=50000000, max_digits=10)),
                ('daily_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway Config',
                'verbose_name_plural': 'Payment Gateway Configs',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('mellat', 'بانک ملت'), ('saderat', 'بانک صادرات'), ('parsian', 'بانک پارسیان'), ('card_to_card', 'کارت به کارت')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('refunded', 'بازپرداخت شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('zarinpal_authority', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_token', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='CardToCardTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_name', models.CharField(max_length=100)),
                ('payer_card_number', models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(message='Card number must be in format: XXXX-XXXX-XXXX-XXXX', regex='^\\d{4}-\\d{4}-\\d{4}-\\d{4}$')])),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer_date', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='card_transfers/')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('expired', 'منقضی شده')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_transfers', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_transfer', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Card to Card Transfer',
                'verbose_name_plural': 'Card to Card Transfers',
                'ordering': ['-created_at'],
            },
        ),
    ]
