# Generated by Django 5.2.8 on 2025-11-10 19:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('battery_life_hours', models.PositiveIntegerField(help_text='Battery life in hours')),
                ('connectivity_type', models.CharField(help_text='GPS, GSM, etc.', max_length=50)),
                ('waterproof_rating', models.CharField(blank=True, max_length=20)),
                ('operating_temperature', models.CharField(blank=True, help_text='e.g., -20°C to +60°C', max_length=20)),
                ('supports_geofencing', models.BooleanField(default=True)),
                ('supports_real_time_tracking', models.BooleanField(default=True)),
                ('has_sos_button', models.BooleanField(default=False)),
                ('has_motion_sensor', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Device Type',
                'verbose_name_plural': 'Device Types',
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('protocol_type', models.CharField(choices=[('mqtt', 'MQTT'), ('http', 'HTTP'), ('tcp', 'TCP'), ('sms', 'SMS')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('default_port', models.PositiveIntegerField(blank=True, null=True)),
                ('requires_authentication', models.BooleanField(default=True)),
                ('supports_encryption', models.BooleanField(default=False)),
                ('message_format', models.JSONField(default=dict, help_text='JSON schema for message format')),
                ('update_frequency_seconds', models.PositiveIntegerField(default=60, help_text='How often device sends updates')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Protocol',
                'verbose_name_plural': 'Protocols',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='IMEI must be 15 digits', regex='^\\d{15}$')])),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(help_text='User-defined device name', max_length=100)),
                ('firmware_version', models.CharField(blank=True, max_length=20)),
                ('config_settings', models.JSONField(default=dict, help_text='Device-specific configuration')),
                ('status', models.CharField(choices=[('inactive', 'غیرفعال'), ('active', 'فعال'), ('suspended', 'معلق'), ('maintenance', 'در حال تعمیر')], default='inactive', max_length=20)),
                ('last_location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_location_time', models.DateTimeField(blank=True, null=True)),
                ('battery_level', models.PositiveIntegerField(blank=True, help_text='Battery percentage', null=True)),
                ('activation_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Subscription expiry', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_devices', to=settings.AUTH_USER_MODEL)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gps_devices.devicetype')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gps_devices.protocol')),
            ],
            options={
                'verbose_name': 'GPS Device',
                'verbose_name_plural': 'GPS Devices',
                'ordering': ['-created_at'],
            },
        ),
    ]
