# Generated by Django 5.2.8 on 2025-11-12 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_id',
            field=models.CharField(blank=True, help_text='Alternative device identifier', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='imei',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='IMEI must be 15 digits', regex='^\\d{15}$')]),
        ),
    ]
