# Generated by Django 5.2.8 on 2025-12-01 06:20

from django.db import migrations

def populate_states(apps, schema_editor):
    State = apps.get_model('gps_devices', 'State')
    states = [
        'park',
        'moving',
        'idle',
        'acc off',
        'sos',
        'vibration',
        'geofence in/out',
        'power cut',
        'low battery',
        'gps lost',
        'gps recovered',
        'tamper (device power cut)',
        'small movement (noise)',
    ]
    for state_name in states:
        State.objects.create(name=state_name)

class Migration(migrations.Migration):

    dependencies = [
        ('gps_devices', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_states),
    ]
