# Generated by Django 5.2.8 on 2025-11-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_devices', '0002_device_device_id_alter_device_imei'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='assigned_port',
            field=models.PositiveIntegerField(blank=True, help_text='Assigned port for the device', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='port_config',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic port settings (e.g., dedicated port or range)'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='dynamic_config',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic settings for the protocol (e.g., server address, port, certificates)'),
        ),
    ]
