# Generated by Django 5.2.8 on 2025-12-01 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_devices', '0002_populate_state_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('protocol_type', models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('HTTP', 'HTTP'), ('MQTT', 'MQTT')], max_length=20)),
                ('default_config', models.JSONField(blank=True, default=dict)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawGpsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processed', 'پردازش شده'), ('rejected', 'رد شده'), ('blocked', 'مسدود شده')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'داده خام GPS',
                'verbose_name_plural': 'داده\u200cهای خام GPS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=20, unique=True)),
                ('sim_no', models.CharField(blank=True, max_length=20, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('maintenance', 'در تعمیر')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_devices', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='gps_devices.model')),
            ],
        ),
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('speed', models.FloatField(default=0)),
                ('heading', models.FloatField(default=0)),
                ('altitude', models.FloatField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('satellites', models.IntegerField(default=0)),
                ('battery_level', models.IntegerField(default=0)),
                ('signal_strength', models.IntegerField(default=0)),
                ('gsm_operator', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_data', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='gps_devices.device')),
            ],
            options={
                'verbose_name': 'موقعیت مکانی',
                'verbose_name_plural': 'موقعیت\u200cهای مکانی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='gps_devices.device')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gps_devices.state')),
                ('location_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gps_devices.locationdata')),
            ],
            options={
                'verbose_name': 'وضعیت دستگاه',
                'verbose_name_plural': 'وضعیت\u200cهای دستگاه',
                'ordering': ['-timestamp'],
            },
        ),
    ]
