# Generated by Django 5.2.8 on 2025-11-15 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_devices', '0003_device_assigned_port_device_port_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawGPSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.TextField(help_text='Raw data received from the device')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Source IP address', null=True)),
                ('processed', models.BooleanField(default=False, help_text='Whether this data has been processed')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='gps_devices.device')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gps_devices.protocol')),
            ],
            options={
                'verbose_name': 'Raw GPS Data',
                'verbose_name_plural': 'Raw GPS Data',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['device', '-received_at'], name='gps_devices_device__880228_idx'), models.Index(fields=['processed', 'received_at'], name='gps_devices_process_24d671_idx')],
            },
        ),
    ]
