# Generated by Django 5.2.8 on 2025-12-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_devices', '0003_model_rawgpsdata_device_locationdata_devicestate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdata',
            name='battery_level',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
