# Generated by Django 5.2.8 on 2025-12-01 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_devices', '0004_alter_locationdata_battery_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawgpsdata',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_data', to='gps_devices.device'),
        ),
    ]
