# Generated by Django 5.2.8 on 2025-11-15 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_devices', '0004_rawgpsdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawgpsdata',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='gps_devices.device'),
        ),
        migrations.AlterField(
            model_name='rawgpsdata',
            name='protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gps_devices.protocol'),
        ),
    ]
