# Generated by Django 5.2.8 on 2025-12-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_devices', '0005_rawgpsdata_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdata',
            name='is_map_matched',
            field=models.BooleanField(default=False, help_text='آیا این نقطه Map Match شده است؟'),
        ),
        migrations.AddField(
            model_name='locationdata',
            name='matched_geometry',
            field=models.TextField(blank=True, help_text='Encoded Polyline دریافتی از API نشان', null=True),
        ),
        migrations.AddField(
            model_name='locationdata',
            name='original_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='مختصات اصلی دریافتی از GPS', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='locationdata',
            name='original_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='مختصات اصلی دریافتی از GPS', max_digits=10, null=True),
        ),
    ]
