# Generated by Django 5.2.8 on 2025-11-19 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_subuser'),
        ('gps_devices', '0006_add_security_fields_rawgpsdata'),
        ('products', '0002_product_products_pr_is_acti_2fee29_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
        migrations.AddField(
            model_name='device',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='device',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, help_text='Device model, e.g., GT06', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='sim_card_number',
            field=models.CharField(blank=True, help_text='SIM card number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='time_zone',
            field=models.CharField(default='+03:30', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='vehicle_type',
            field=models.CharField(blank=True, help_text='Type of vehicle', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gps_devices.devicetype'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, help_text='User-defined device name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='products.product'),
        ),
        migrations.AlterField(
            model_name='device',
            name='protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gps_devices.protocol'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
