# Generated by Django 5.2.8 on 2025-12-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_devices', '0006_locationdata_is_map_matched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdata',
            name='location_source',
            field=models.CharField(default='GPS', help_text='Source of location data (GPS, LBS, etc.)', max_length=20),
        ),
    ]
