# Generated by Django 5.2.8 on 2025-12-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_devices', '0007_locationdata_location_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdata',
            name='alarm_type',
            field=models.CharField(blank=True, help_text='Type of alarm (SOS, Overspeed, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='locationdata',
            name='is_alarm',
            field=models.BooleanField(default=False, help_text='True if this location is an alarm/SOS'),
        ),
    ]
