# Generated by Django 5.2.8 on 2025-11-19 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_devices', '0007_remove_device_user_device_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedGPSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.TextField(help_text='Raw data received from the device')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Source IP address', null=True)),
                ('status', models.CharField(default='blocked', help_text='Status set to blocked', max_length=20)),
                ('processed', models.BooleanField(default=False, help_text='Whether this data has been processed')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for blocking')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_raw_data', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_data', to='gps_devices.device')),
                ('protocol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gps_devices.protocol')),
            ],
            options={
                'verbose_name': 'Blocked GPS Data',
                'verbose_name_plural': 'Blocked GPS Data',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='GPSPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='GPS device model name', max_length=100)),
                ('pattern', models.TextField(help_text='Generated regex pattern for raw_data')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address associated with this pattern')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, help_text='Assigned device if any', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gps_devices.device')),
            ],
            options={
                'verbose_name': 'GPS Pattern',
                'verbose_name_plural': 'GPS Patterns',
            },
        ),
    ]
