# Generated by Django 5.2.8 on 2025-11-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_devices', '0008_blockedgpsdata_gpspattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawgpsdata',
            name='unknown_sections',
            field=models.JSONField(blank=True, default=dict, help_text='Unknown sections from parsed GPS data'),
        ),
    ]
