# Generated by Django 5.2.8 on 2025-12-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_devices', '0008_locationdata_alarm_type_locationdata_is_alarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='consecutive_count',
            field=models.JSONField(blank=True, default=dict, help_text='Tracks consecutive occurrences of packet types/states'),
        ),
        migrations.AddField(
            model_name='locationdata',
            name='packet_type',
            field=models.CharField(blank=True, help_text='Type of packet (V1, HB, SOS, etc.)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='locationdata',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='locationdata',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
