# Generated by Django 5.2.8 on 2025-11-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_devices', '0009_rawgpsdata_unknown_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('inactive', 'غیرفعال'), ('active', 'فعال'), ('suspended', 'معلق'), ('maintenance', 'در حال تعمیر')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='rawgpsdata',
            name='unknown_sections',
            field=models.JSONField(blank=True, default=dict, help_text='Unknown sections from parsed GPS data', null=True),
        ),
    ]
