# Generated by Django 5.2.8 on 2025-12-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_devices', '0009_device_consecutive_count_locationdata_packet_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaliciousPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.TextField(help_text='الگوی مخرب (می\u200cتواند متن یا hex باشد)', unique=True)),
                ('pattern_type', models.CharField(choices=[('exact', 'تطابق دقیق'), ('startswith', 'شروع با'), ('contains', 'شامل'), ('regex', 'عبارت منظم')], default='contains', help_text='نوع تطابق', max_length=20)),
                ('description', models.CharField(blank=True, help_text='توضیحات الگو', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='فعال/غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hit_count', models.IntegerField(default=0, help_text='تعداد دفعات تشخیص')),
                ('last_hit', models.DateTimeField(blank=True, help_text='آخرین بار تشخیص', null=True)),
            ],
            options={
                'verbose_name': 'الگوی مخرب',
                'verbose_name_plural': 'الگوهای مخرب',
                'db_table': 'malicious_patterns',
                'ordering': ['-created_at'],
            },
        ),
    ]
