# Generated by Django 5.2.8 on 2025-12-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_devices', '0010_maliciouspattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='maliciouspattern',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='آدرس IP مخرب (اختیاری)', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='maliciouspattern',
            unique_together={('pattern', 'ip_address')},
        ),
    ]
