# Generated by Django 5.2.8 on 2025-12-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_devices', '0011_maliciouspattern_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdata',
            name='cid',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='locationdata',
            name='lac',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='locationdata',
            name='mcc',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='locationdata',
            name='mnc',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='locationdata',
            name='satellites',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='locationdata',
            name='signal_strength',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
