# Generated by Django 5.2.8 on 2025-12-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_devices', '0012_locationdata_cid_locationdata_lac_locationdata_mcc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdata',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_index=True, help_text='زمان واقعی گزارش شده توسط دستگاه', null=True),
        ),
    ]
