# Generated by Django 5.2.8 on 2025-11-10 19:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gps_devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('shape', models.CharField(choices=[('circle', 'Circle'), ('polygon', 'Polygon')], default='circle', max_length=10)),
                ('center_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('center_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('radius', models.DecimalField(blank=True, decimal_places=2, help_text='Radius in meters', max_digits=6, null=True)),
                ('polygon_points', models.JSONField(default=list, help_text='List of [lat, lng] points for polygon')),
                ('alert_on_enter', models.BooleanField(default=True)),
                ('alert_on_exit', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Geofence',
                'verbose_name_plural': 'Geofences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, help_text='Altitude in meters', max_digits=7, null=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, help_text='Speed in km/h', max_digits=5, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, help_text='Heading in degrees', max_digits=5, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in meters', max_digits=4, null=True)),
                ('battery_level', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('signal_strength', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('raw_data', models.JSONField(default=dict, help_text='Raw GPS data from device')),
                ('address', models.CharField(blank=True, help_text='Reverse geocoded address', max_length=255)),
                ('timestamp', models.DateTimeField(help_text='When the location was recorded')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When data was received by server')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_data', to='gps_devices.device')),
            ],
            options={
                'verbose_name': 'Location Data',
                'verbose_name_plural': 'Location Data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('geofence_enter', 'ورود به منطقه محدود'), ('geofence_exit', 'خروج از منطقه محدود'), ('low_battery', 'باتری کم'), ('device_offline', 'دستگاه آفلاین'), ('sos_button', 'دکمه SOS'), ('speed_limit', 'تجاوز از سرعت مجاز')], max_length=20)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('critical', 'بحرانی')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('push_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='gps_devices.device')),
                ('location_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.locationdata')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='locationdata',
            index=models.Index(fields=['device', '-timestamp'], name='tracking_lo_device__8e78eb_idx'),
        ),
        migrations.AddIndex(
            model_name='locationdata',
            index=models.Index(fields=['latitude', 'longitude'], name='tracking_lo_latitud_a1d3f4_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['device', '-created_at'], name='tracking_al_device__ea314a_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_read', 'is_resolved'], name='tracking_al_is_read_8d8e89_idx'),
        ),
    ]
