# Generated by Django 5.2.8 on 2025-11-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps_devices', '0007_remove_device_user_device_customer_and_more'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type'], name='tracking_al_alert_t_845c35_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity'], name='tracking_al_severit_099b20_idx'),
        ),
        migrations.AddIndex(
            model_name='locationdata',
            index=models.Index(fields=['timestamp'], name='tracking_lo_timesta_b7e871_idx'),
        ),
        migrations.AddIndex(
            model_name='locationdata',
            index=models.Index(fields=['device', 'timestamp'], name='tracking_lo_device__c4822e_idx'),
        ),
    ]
