# Generated by Django 5.2.8 on 2025-11-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('module', models.CharField(blank=True, max_length=100)),
                ('function', models.CharField(blank=True, max_length=100)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('process_id', models.PositiveIntegerField(blank=True, null=True)),
                ('thread_id', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='admin_panel_created_aab3a1_idx'), models.Index(fields=['level'], name='admin_panel_level_99571b_idx'), models.Index(fields=['module'], name='admin_panel_module_3f35a6_idx')],
            },
        ),
    ]
