# Generated by Django 5.2.8 on 2025-11-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-created_at'], 'verbose_name': 'Admin User Notification', 'verbose_name_plural': 'Admin User Notifications'},
        ),
        migrations.AlterField(
            model_name='log',
            name='line_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='process_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='thread_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
